### ISSUE TITLE
Güncel şirket bilgileri

### ISSUE THREAD

**Issue by hgunay** [sdogruyol/gencleredestek.com#10]
Selamlar,
Excel'deki şirket bilgileri ile sitedeki bilgiler eşleşmiyor. Excel'de güncellenen şirket bilgileri ne kadar sürede siteye yansıyor?
Avantajlar ve Etkinlikler kısmındaki ortak veriler belki farklı kolonlara alınıp Evet/Hayır şeklinde seçmeli hale getirildikten sonra arayüzde de böyle bir geliştirme yapılabilir. Hem de filtreleme de kolaylık sağlar gençlere :)

**Comment by akardev** [comment]
Şirketlerin açık pozisyonları da görüntülenebilir.

**Comment by hasanmumin** [comment]
Spreadsheets yerine typeform ile yeni firma girişi eklerseniz çok daha rahat olur.

**Comment by sdogruyol** [comment]
@hasanmumin çok haklısınız, Airtable ya da Typeform gibi birşeye geçiş yapacağız 👍

**Comment by hasanmumin** [comment]
@sdogruyol 2 hafta kadar önce firma kayıt ettim ama halen yayınlanmış durumda değil.

**Comment by enespolat24** [comment]
Merhaba , biz de Epigra olarak bilgilerimizi güncelledik. Müsait olduğunuzda güncelleyebilir misiniz ?

**Comment by sdogruyol** [comment]
@enespolat24 çok teşekkürler. Güncellendi 👍
