### ISSUE TITLE
İletişime geç butonu düzgün gözükmüyor.

### ISSUE THREAD

**Issue by Furkangunduz** [sdogruyol/gencleredestek.com#11]
![image](https://user-images.githubusercontent.com/81353673/185626655-718c377b-8d9d-4965-9079-6213ca6a3e28.png)

**Comment by Furkangunduz** [comment]
Buttonların içerisinde bulunduğu div elementine: 
    display:flex;
    justify-content:center;
    align-items:center;

Buttonların kendisine de : 
    white-space: nowrap;

Css'leri uygulanarak sorun çözülebiliyor.

**Comment by sdogruyol** [comment]
Çok teşekkürler @Furkangunduz 🙏 PR açmak istersen, seve seve 👍

**Comment by Furkangunduz** [comment]
@sdogruyol PR açmak niyetindeydim fakat daha önce ruby kullanmadığım için ruby versiyonunda biraz sorun yaşadım.
O yüzden maalesef PR açamıyorum

**Comment by sdogruyol** [comment]
Bunu hali hazırda düzelmişiz zaten 👍 
Not: 2 sene sonra gelen update 🤣
