### ISSUE TITLE
Firmamızı çıkarmak için ne yapmalıyız :(

### ISSUE THREAD

**Issue by tilbak** [sdogruyol/gencleredestek.com#15]
Merhaba, bizim aktif ilanımız olmadığı için derneğimizi(Kafessiz Türkiye) listened çıkartmak istiyoruz, nasıl yapmalıyız bir iletişim adresi vsde bulamadım buraya yazıyorum o yüzden. Çok teşekkürler

**Comment by sdogruyol** [comment]
Kusura bakmayın yoğunluktan şimdi gördüm mesajınızı. Hemen çıkartıyorum
