### ISSUE TITLE
Şirket kutularındaki linklerin yeri

### ISSUE THREAD

**Issue by enderahmetyurt** [sdogruyol/gencleredestek.com#8]
Merhaba 👋 

![Screen Shot 2022-04-23 at 11 10 19](https://user-images.githubusercontent.com/447588/164886291-afd3c0ce-9cfc-4f10-8b47-1cfe0c151757.png)

`Websitesi` ve `Iletişime Geç` linklerinin olduğu div bu şekilde değil de hep aynı yerde altta dursa sanki daha tutarlı durur gibi geldi bana. Ne dersiniz?

Css bilgim yetmedi yapmaya 🥺

**Comment by sdogruyol** [comment]
Benim de css yetmiyor ne dersin @turhansel 🤔

**Comment by turhansel** [comment]
bir bakayım 👍🏼
